version: '2.2'
services:
  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./api/Dockerfile
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV="development"
  #     - PORT=3001
  #     - JWT_SECRET="supersecret"
  #     - POSTGRES_HOST="localhost"
  #     - POSTGRES_DB_NAME="react-node-template"
  #     - POSTGRES_USER="api"
  #     - POSTGRES_PASSWORD="password"
  #
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: powerPlay
      POSTGRES_USER: powerPlay-user
      POSTGRES_PASSWORD: test123
    ports:
      - '5432:5432'
    volumes:
      - ./packages/data/src/migrations:/docker-entrypoint-initdb.d
      - '/var/run/docker.sock:/var/run/docker.sock'
